version: '2.1'
services:

  admin:
    image: adminer:4.3
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./db/ 
    ports:
      - "4306:3306"
    volumes: 
      - "/var/lib/mysql"
    healthcheck:
      test: echo db service healthy
      interval: 80s
      timeout: 80s
      retries: 10

  lfr:
    build: ./liferay/
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./liferay:/etc/liferay/mount